[package]
name = "fabricatio-{{ cookiecutter.project_name }}"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]

pyo3 = { version = "0.24.2", features = ["extension-module"] }



[workspace]